# Generated by Django 3.2.9 on 2021-12-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_image_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile_pics/default.png', upload_to='images/profile_pics'),
        ),
    ]
