# Generated by Django 3.2.9 on 2021-12-05 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='creator_profile',
            new_name='author',
        ),
    ]
