# Generated by Django 3.2.9 on 2021-12-05 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_auto_20211206_0229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='full_name',
        ),
    ]
